---
title: 'Homework #6'
author: "Eric Pettengill"
output: pdf_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ISLR)
library(splines)
library(broom)
library(ggformula)
library(patchwork)
```

### (1) Cubic spline with 3 knots at 25th, 50th, and 75th percentiles.

```{r}
splines.fit <- lm(mpg ~ bs(horsepower, df = 6), data = Auto)

glance(splines.fit)
```

### (2) Natural spline with 3 knots at 25th, 50th, and 75th percentile

```{r}
natural.splines.fit <- lm(mpg ~ ns(horsepower, df = 4), data = Auto)

glance(natural.splines.fit)
```

### (3) Smoothing spline with lambda chosen by cross validation

```{r}
smooth.fit <- smooth.spline(Auto$horsepower, Auto$mpg, cv = FALSE)

glance(smooth.fit)
```

### (4) Local regression with span = 0.75

```{r}
local.fit <- loess(mpg ~ horsepower, data = Auto, span = 0.75)

summary(local.fit)
```

### Plot

Each methods fit is plotted below. The cubic spline in red, natural spline in blue, local regression in green, and the smoothing spline in black.

```{r}
ns <- ggplot(Auto, aes(x = horsepower, y = mpg)) +
  geom_point(size = 1/3) +
  geom_smooth(method = lm, formula = y ~ ns(x, df = 4), color = "blue", se = FALSE) 

cs <- ggplot(Auto, aes(x = horsepower, y = mpg)) +
  geom_point(size = 1/3) +
  geom_smooth(method = lm, formula = y ~ bs(x, df = 6), color = "red", se = FALSE)

loc <- ggplot(Auto, aes(x = horsepower, y = mpg)) +
  geom_point(size = 1/3) +
  geom_smooth(method = loess, span = 0.75, se = FALSE, color = "green")

ss <- ggplot(Auto, aes(x = horsepower, y = mpg)) +
  geom_point(size = 1/3) +
  geom_spline(df = smooth.fit$df)

(cs + ns)/(loc + ss)
```


